homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 224
  unit_system: imperial
  time_zone: America/Indiana/Indianapolis
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  base_url: !secret base_url
  api_password: !secret http_password
  ssl_certificate: /home/homeassistant/fullchain.pem
  ssl_key: /home/homeassistant/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 4   

updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time
history:
  exclude:
    entities:
      - sensor.date
      - sensor.date__time
      - sensor.time__date
      - sensor.time
      - sensor.time_utc

# View all events in a logbook
logbook:
  exclude:
    entities:
      - sensor.date
      - sensor.date__time
      - sensor.time__date
      - sensor.time
      - sensor.time_utc

# Enables a map showing the location of tracked devices
#map:

# Track the sun
sun:

# Store input states
recorder:

binary_sensor:
  - platform: ring

# Text to speech
tts:
  - platform: google
    cache: true
    time_memory: 300

group: !include_dir_merge_named groups
automation: !include automations.yaml
automation old: !include_dir_merge_list automations
script: !include_dir_merge_named scripts
envisalink: !include includes/envisalink.yaml
sensor: !include includes/sensor.yaml
device_tracker: !include includes/device_tracker.yaml
zwave: !include includes/zwave.yaml
media_player: !include includes/media_player.yaml
google_assistant: !include includes/google_assistant.yaml
climate: !include includes/climate.yaml
emulated_hue: !include includes/emulated_hue.yaml
notify: !include includes/notify.yaml
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
camera: !include includes/camera.yaml

ring:
  username: !secret ring_user
  password: !secret ring_pass

#mqtt:
#  broker: 10.0.3.17
#  discovery: true
#  discovery_prefix: smartthings

#switch:
#  - platform: mqtt
#    name: "Kitchen Lights"
#    state_topic: "smartthings/Kitchen Lights/switch"
#    command_topic: "smartthings/Kitchen Lights/switch"
#    payload_on: "on"
#    payload_off: "off"
#    retain: true

#locksinterface:
#panel_custom:
#  - name: locks
#    sidebar_title: ZWave Locks
#    sidebar_icon: mdi:lock
