# Alarm system related automations
- alias: 'Set alarm when everyone leaves'
  trigger:
    platform: state
    entity_id: input_select.home_mode
    to: 'Away'
  condition:
    condition: template
    value_template: "{{ states('alarm_control_panel.home_alarm') != 'Armed away' }}"
  action:
    - service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.home_alarm
    - service: script.notify_important
      data_template:
        message: 'Everyone left and the alarm is off, setting away now'
#Add automations to disarm when certain codes are used at lock