### Alarm system related automations

# Forgot to set the alarm
- alias: 'Set alarm when everyone leaves'
  trigger:
    platform: state
    entity_id: input_select.home_mode
    to: 'Away'
  condition:
    condition: state
    entity_id: alarm_control_panel.home_alarm
    state: 'disarmed'
  action:
    - service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.home_alarm
    - service: script.notify_important
      data_template:
        message: 'Everyone left and the alarm is off, setting away now'

# TODO: Make this less terrible
- alias: "Disarm alarm with Sarah or David's code"
  trigger:
    platform: time
    seconds: '/1'
  condition:
    condition: or
    conditions:
      - condition: template
        value_template: "{% if as_timestamp(now()) - as_timestamp(states.sensor.schlage_fe599gr_wireless_door_lock_alarm_level.last_changed) < 1 and is_state('sensor.garage_lock_alarm_type', '16') and is_state('sensor.garage_lock_alarm_level', '1') %} true {% endif %}"
      - condition: template
        value_template: "{% if as_timestamp(now()) - as_timestamp(states.sensor.schlage_fe599gr_wireless_door_lock_alarm_level.last_changed) < 1 and is_state('sensor.garage_lock_alarm_type', '16') and is_state('sensor.garage_lock_alarm_level', '2') %} true {% endif %}"
  action:
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.home_alarm
    - service: script.notify_david_only
      data_template:
        message: "Disarming based on garage lock code"