- alias: "Low Battery Notification"
  hide_entity: true
  trigger:
    - platform: template
      value_template: >
        {% for zwave in states.zwave if zwave.attributes.battery_level %}
          {%- if zwave.attributes.battery_level | int < 20 -%}
            {{true}}
          {%- endif -%}
        {%- endfor -%}
  action:
    - service: script.notify_important
      data_template:
        message: >
          {{ trigger.to_state.attributes.friendly_name }} battery low