### Automations related to the garage doors

- alias: 'Garage Door Sarah Left Open'
  hide_entity: true
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.garage_door_sarah
    to: 'on'
    for:
      minutes: 5
  action:
    service: script.notify_important
    data_template:
      message: "Sarah's garage door left open for 5 minutes"

- alias: 'Garage Door David Left Open'
  hide_entity: true
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.garage_door_david
    to: 'on'
    for:
      minutes: 5
  action:
    service: script.notify_important
    data_template:
      message: "David's garage door left open for 5 minutes"

- alias: 'Garage door left open when alarm set'
  hide_entity: true
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: alarm_control_panel.home_alarm
    to: 'armed_home'
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: binary_sensor.garage_door_david
      state: 'on'
    - condition: state
      entity_id: binary_sensor.garage_door_sarah
      state: 'on'
  action:
    service: script.notify_important
    data_template:
      message: "A garage door is still open and the alarm was set"

#TODO: consider a TTS notification for this since it's bad
- alias: 'Garage door opened while alarm set in home mode'
  hide_entity: true
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.garage_door_david
      to: 'on'
    - platform: state
      entity_id: binary_sensor.garage_door_david
      to: 'on'
  condition:
    condition: state
    entity_id: alarm_control_panel.home_alarm
    state: 'armed_home'
  action:
    service: script.notify_important
    data_template:
      message: "A garage door is still open and the alarm was set"