### Automations for dryer and washing machine completion

- alias: 'Washing machine done'
  trigger:
    platform: state
    entity_id: binary_sensor.washing_machine_status
    to: 'off'
  action:
    - service: script.notify_status
      data_template:
        message: 'Washing machine done'

- alias: 'Dryer done'
  trigger:
    platform: state
    entity_id: binary_sensor.dryer_status
    to: 'off'
  action:
    - service: script.notify_status
      data_template:
        message: 'Dryer done'


- alias: 'Dryer done voice'
  trigger:
    platform: state
    entity_id: binary_sensor.dryer_status
    to: 'off'
  condition:
    condition: time
    after: '08:00:00'
    before: '23:00:00'
  action:
    - service: script.notify_audio_all
      data_template:
        message: 'Dryer is done'

- alias: 'Washing machine done voice'
  trigger:
    platform: state
    entity_id: binary_sensor.washing_machine_status
    to: 'off'
  condition:
    condition: time
    after: '08:00:00'
    before: '23:00:00'
  action:
    - service: script.notify_audio_all
      data_template:
        message: 'Washing machine is done'