- alias: 'Washing machine done'
  trigger:
    platform: state
    entity_id: sensor.washing_machine_status
    to: 'Off'
  action:
    - service: script.notify_status
      data_template:
        message: 'Washing machine done'

- alias: 'Dryer done'
  trigger:
    platform: state
    entity_id: sensor.dryer_status
    to: 'Off'
  action:
    - service: script.notify_status
      data_template:
        message: 'Dryer done'