### Automations to adjust the thermostats

- alias: 'Thermostats - night'
  trigger:
    platform: time
    at: '00:00:00'
  action:
    - service: script.thermostats_night

- alias: 'Thermostats - home'
  trigger:
    platform: time
    at: '17:00:00'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: script.thermostats_home

- alias: 'Thermostats - vacation'
  trigger:
    platform: state
    entity_id: input_select.home_mode
    to: 'Vacation'
  action:
    - service: script.thermostats_away

- alias: 'Thermostats - weekend'
  trigger:
    platform: time
    at: '07:30:00'
  condition:
    condition: time
    weekday:
      - sat
      - sun
  action:
    - service: script.thermostats_home