- alias: 'Turn theromstats to night mode'
  trigger:
    platform: time
    at: '00:00:00'
  action:
    - service: script.thermostats_night

- alias: 'Turn theromstats to home mode'
  trigger:
    platform: time
    at: '17:00:00'
  action:
    - service: script.thermostats_home

- alias: 'Set thermostats vacation mode'
  trigger:
    platform: state
    entity_id: input_select.home_mode
    to: 'Vacation'
  action:
    - service: script.thermostats_away