- platform: unifi
  host: !secret unifi_host
  username: !secret unifi_user
  password: !secret unifi_pass
  verify_ssl: false
  track_new_devices: false
  detection_time: 30
  ssid_filter:
    - !secret unifi_ssid1
    - !secret unifi_ssid2
    - !secret unifi_ssid3