- platform: wunderground
  api_key: !secret wunderground_api
  monitored_conditions:
    - temp_f 
#- platform: fastdotcom
#  minute: 30
#  hour:
#    - 0
#    - 6
#    - 12
#    - 18
#if (as_timestamp(now()) - as_timestamp(sensor.schlage_fe599gr_wireless_door_lock_alarm_level) < 10) 
- platform: template
  sensors:
    test_door_code:
      friendly_name: 'Time based FE599 test'
      value_template: >-
        {% if as_timestamp(now()) - as_timestamp(states.sensor.schlage_fe599gr_wireless_door_lock_alarm_level.last_changed) < 5 and is_state('sensor.schlage_fe599gr_wireless_door_lock_alarm_type', '16') %}
          {{ states.sensor.schlage_fe599gr_wireless_door_lock_alarm_level.state }}
        {% else %}
          0
        {% endif %}

- platform: template
  sensors:
    test_door_code_no_time:
      friendly_name: 'Non-time based FE599 test'
      value_template: >-
        {% if is_state('sensor.schlage_fe599gr_wireless_door_lock_alarm_type', '16') %}
          {{ states.sensor.schlage_fe599gr_wireless_door_lock_alarm_level.state }}
        {% else %}
          0
        {% endif %}


- platform: template
  sensors:
    garage_code_unlocked:
      friendly_name: "Code used to unlock garage lock"
      value_template: >
        {% if is_state('sensor.garage_lock_alarm_level', '1') and is_state('sensor.garage_lock_alarm_type', '16') %}
          U1
        {% elif is_state('sensor.garage_lock_alarm_level', '2') and is_state('sensor.garage_lock_alarm_type', '16') %}
          U2
        {% endif %}

- platform: template
  sensors:
    washing_machine_status:
      friendly_name: "Washing machine status"
      value_template: >
        {% if states('sensor.washing_machine_power') | int > 1 %}
          Running
        {% else %}
          Off
        {% endif %}
    dryer_status:
      friendly_name: "Dryer status"
      value_template: >
        {% if states('sensor.dryer_burglar') | int == 2 %}
          Running
        {% else %}
          Off
        {% endif %}

# TODO: add smoke detector battery
- platform: template
  sensors:
    dryer_battery:
      friendly_name: "Dryer sensor battery"
      value_template: '{{ states.zwave.dryer.attributes.battery_level }}'
      unit_of_measurement: '%'
    garage_lock_battery:
      friendly_name: "Garage lock battery"
      value_template: '{{ states.zwave.garage_lock.attributes.battery_level }}'
      unit_of_measurement: '%'
    deck_lock_battery:
      friendly_name: "Deck lock battery"
      value_template: '{{ states.zwave.deck_lock.attributes.battery_level }}'
      unit_of_measurement: '%'
    garage_door_sarah_battery:
      friendly_name: "Garage door Sarah sensor battery"
      value_template: '{{ states.zwave.garage_door_sarah.attributes.battery_level }}'
      unit_of_measurement: '%'
    garage_door_david_battery:
      friendly_name: "Garage door David sensor battery"
      value_template: '{{ states.zwave.garage_door_david.attributes.battery_level }}'
      unit_of_measurement: '%'
    multisensor_1_battery:
      friendly_name: "Multisensor 1 battery"
      value_template: '{{ states.zwave.multisensor_1.attributes.battery_level }}'
      unit_of_measurement: '%'

# From: https://github.com/master-kenobi/ha-alarmclock
- platform: template
  sensors:
    alarm_time:
      friendly_name: 'Time'
      value_template: '{{ "%0.02d:%0.02d" | format(states("input_number.alarmhour") | int, states("input_number.alarmminutes") | int) }}'
- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'time_date'
    - 'time_utc'